services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    container_name: "auth-api"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: "redis"
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: "postgres"
